### ISSUE TITLE
Error pop-up on loading pages: toUpperFirst() of undefined

### ISSUE THREAD

**Issue by EirikOsnes** [ryceg/Eigengrau-s-Essential-Establishment-Generator#279] opened 2020-06-08 16:27 UTC
In Chrome:
When opening any number of pages (NPCs, shops, guilds and more) error pop-ups appear. Most of these seem to be similar: 
![image](https://user-images.githubusercontent.com/25607450/84055762-9576ff80-a9b5-11ea-956b-5fbce62fc854.png)

**Comment by ryceg** [comment] 2020-06-10 02:30
Duplicate of #267

**Closed by ryceg** 2020-06-10 02:30 UTC
Labels: bug, duplicate
