### ISSUE TITLE
A few features and thanks

### ISSUE THREAD

**Issue by JamesDWG** [ryceg/Eigengrau-s-Essential-Establishment-Generator#662] opened 2021-08-04 12:10 UTC
Ok. So I want to say that I love the program and it is incredibly useful. Yet nothing can stop my DM brain from going What if it....

So I have a few suggestions that I would find useful. I'm sure you get a ton of these so thanks either way for the hard work you do on this.

1) Ability to Create New Buildings as you can do with Factions.
2) Easier way (or some sort of walk-through) to add custom Pantheons. It may be easier than it looks, but I found I was unsure how to proceed.
3) More extensive 'Harvest' and 'Region Rich' lists. Would be great if there was a 'Nothing' option for both as well. Good for a destitute village.
4) A more obvious "I am starting a new town" button somewhere on the sidebar. 

Thanks again for all of the hard work. I have no ability to code or build in html on any real level. But I could try to help flesh out the lists from 3 if you would like. My email is james10872@aol.com not sure how often I will be on GitHub to see any responses.

**Comment by ryceg** [comment] 2021-08-15 07:55
Hi @JamesDWG thanks for the feedback. Please do not take my closing your post as a dismissal, GitHub Issues are for the developer, and need to be as descriptive as possible so other people know what the issue is. The issues you raised are already being addressed elsewhere.

1. This is already a feature.
2. This is planned.
3. This is planned as part of the Economy update, and is a duplicate of #481 
4. This is a good idea, and I am working with a UX designer to figure out the easiest way of making it clear.

**Closed by ryceg** 2021-08-15 07:55 UTC
