### ISSUE TITLE
Being able to save scenarios made by the quick generator would be nice

### ISSUE THREAD

**Issue by trapbuilder2** [ryceg/Eigengrau-s-Essential-Establishment-Generator#296] opened 2020-06-11 20:34 UTC
I recently generated a rather nice scenario that I would have liked to use in my upcoming campaign. I used the save function, and closed the tab. When I came back to the save, it had only saved the generated hamlet, and not the scenario.

I feel this could be solved by either saving the last generated scenario with the rest of the page, or a separate save system for the scenario generator would work very well.

**Comment by ryceg** [comment] 2020-06-11 23:13
This is a duplicate issue of #261. Investigating this issue, I was able to reproduce your issue only when I went directly from generating the scenario to saving the town. This is due to the way that the engine handles saves; it keeps a history of navigation, which is what the save file is a part of. By not navigating to another page before saving, it only saves the initial state.

**To restore the scenario**: Navigate to the hash, and then reproduce the steps taken to get the scenario- if you generated 3 mountain encounters and then a town encounter, do that. Because it uses PRNG it will be in exactly the same order.

**Temporary fix**: navigate to one of the buildings and back before saving to retain the scenario created.

**Permanent fix**: will be implemented in the next public update.

**Closed by ryceg** 2020-06-11 23:13 UTC
Labels: duplicate
