### ISSUE TITLE
description block bug after editing

### ISSUE THREAD

**Issue by logitek184** [ryceg/Eigengrau-s-Essential-Establishment-Generator#712] opened 2022-04-02 06:42 UTC
**Describe the bug**

after editing attributes and demographics the description block doesn't change

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info):

https://eigengrausgenerator.com/?seed=onerlookedimperfectbufflehead

Page to navigate to, buttons to press, etc:

1. generate town
2. click Detailed description of (town name)
3. click edit town
5. edit attributes
6. edit racial demographics
7. save changes
8. go back to detailed description
9. town description of demographics doesn't change

**Additional context**

**Comment by ryceg** [comment] 2022-04-12 07:25
Closing as it is a duplicate of  #645

**Closed by ryceg** 2022-04-12 07:25 UTC
