### ISSUE TITLE
Demographics bug

### ISSUE THREAD

**Issue by Rinzlers** [ryceg/Eigengrau-s-Essential-Establishment-Generator#659] opened 2021-07-31 17:58 UTC
I set up a town that was 94% Dwarven and the result was not reflected in the generated result.  
[eigengraus-generator-20210730-200942.zip](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/files/6911646/eigengraus-generator-20210730-200942.zip)

**Comment by ryceg** [comment] 2021-08-15 07:59
Closing as this is a duplicate of #645

**Closed by ryceg** 2021-08-15 07:59 UTC
