### ISSUE TITLE
Error: <<set>>: bad evaluation: keyTarget is undefined.

### ISSUE THREAD

**Issue by gendernihilist** [ryceg/Eigengrau-s-Essential-Establishment-Generator#281] opened 2020-06-08 16:37 UTC
The following happened when I tried Summer and Mountain and clicked Create Scenario. Sometimes it works and sometimes I get an error that is either the same as this or similar to this, I didn't check to see if the numbers lined up between instances of this error. 

> Apologies! An error has occurred. You may be able to continue, but some parts may not work properly.

```
Error: <<set>>: bad evaluation: keyTarget is undefined.

Stack Trace:
value@https://eigengrausgenerator.com/:56169:12767
handler/<@https://eigengrausgenerator.com/:56171:2061
value/<@https://eigengrausgenerator.com/:56170:19446
t/<@https://eigengrausgenerator.com/:56167:119
dispatch@https://eigengrausgenerator.com/:59:42571
add/v.handle@https://eigengrausgenerator.com/:59:40572
```

**Comment by ryceg** [comment] 2020-06-09 00:12
Closing as this is a duplicate of #276

**Closed by ryceg** 2020-06-09 00:12 UTC
Labels: bug
