### ISSUE TITLE
Updating Issue When Relevant Data is changed

### ISSUE THREAD

**Issue by ammogar** [ryceg/Eigengrau-s-Essential-Establishment-Generator#581] opened 2021-04-16 21:15 UTC
I was messing about your amazing generator when I started customizing a town that I've done much of the legwork on. I changed the name and the demographics without any issue. However, it still referred back to the base information from when it was generated and still referred to Halflings as the most prominent race.

Also, adding some of the new wavetop official races (Aasimar would be fine doesn't need to get specific to the Fallen or the other two variants that I can't recall off the top of my head), or allowing people to add a race, would be helpful to this end.

Also, I just recalled that one of the character descriptions glitched the screen whenever I hovered over it. I had just generated the brothel and was clicking through the harlots. When I tried to figure out what race they were, by hovering over the hyperlinked name. It causes the description box to flicker.

**Comment by ryceg** [comment] 2021-04-17 09:58
Hi, thanks for the kind words. In future, please keep to one issue per ticket, and [follow the template](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#why-do-i-need-to-give-exact-steps-to-reproduce-a-bug). Data not updating is a duplicate of #503. 

As for your second issue, we add races when Deity tier Patrons request that we add one, or a community member provides us with the requisite name lists and data (Lizardfolk were added in the last major update from community contributions).

We cannot help your third issue without exact steps to reproduce.

**Closed by ryceg** 2021-04-17 09:58 UTC
