### ISSUE TITLE
Inn room prices and availability not working

### ISSUE THREAD

**Issue by arthur-bauer** [ryceg/Eigengrau-s-Essential-Establishment-Generator#431] opened 2020-12-19 12:56 UTC
**Describe the bug**

After generating an inn, several details like inn room prices or room availability, doesn't work.

`Rent a room for the night
The Maiden and Stone has 5 available rooms, which are large and Error: <<print>>: bad evaluation: cleanliness.find is not a function. (In 'cleanliness.find(([threshold]) => { return threshold <= tavern.roll.bedCleanliness })', 'cleanliness.find' is undefined). Because this inn is priced for squalid patrons, it will cost Error: cannot execute widget <<money>>: unable to parse macro argument "setup.getTavernLodging($building)": wealth.find is not a function. (In 'wealth.find(([threshold]) => { return threshold <= tavern.roll.wealth })', 'wealth.find' is undefined) to stay here for the night. `

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): /#prestigiousoffbeatmammoth

Navigate to the inn _The Maiden and Stone_

**Additional context**

**Comment by ryceg** [comment] 2020-12-19 21:42
Thanks for this- this is a duplicate of #410 and has been fixed in the dev build.

**Closed by ryceg** 2020-12-19 21:42 UTC
