### ISSUE TITLE
Room in Tavern not pulling details

### ISSUE THREAD

**Issue by triet43** [ryceg/Eigengrau-s-Essential-Establishment-Generator#416] opened 2020-12-05 02:08 UTC
When clicking to rent a room for the night in a tavern, the room is not pulling details. 

**To Reproduce (bugs MUST be replicable)**

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info): https://eigengrausgenerator.com/#nimblepuzzlingcanadagoose

Page to navigate to, buttons to press, etc:
<img width="446" alt="Screen Shot 2020-12-04 at 19 54 00" src="https://user-images.githubusercontent.com/75511052/101230680-62fc4580-366c-11eb-936d-3124ddb0d13d.png">

**Additional context**

**Comment by ryceg** [comment] 2020-12-06 13:03
Thanks for this- it is a duplicate of #410 and has been fixed in dev, and will be pushed to live in the next update :)

**Closed by ryceg** 2020-12-06 13:03 UTC
