### ISSUE TITLE
Name Changes and NPC Changes

### ISSUE THREAD

**Issue by gendernihilist** [ryceg/Eigengrau-s-Essential-Establishment-Generator#285] opened 2020-06-08 18:58 UTC
I wish when you changed the name of the community the buildings would reflect the new name rather than holding onto the original name, or at least that you could delete the buildings as well as generate new ones to remove references to a community it no longer is.

Same with NPCs that you delete, I wish you could generate an NPC for an organization (like a militia) that could replace an NPC you delete so there isn't just an error field that never gets fixed.

**Comment by ryceg** [comment] 2020-06-09 00:11
Closing as this is a partial duplicate of #274.

**Closed by ryceg** 2020-06-09 00:11 UTC
