### ISSUE TITLE
Undefined error when opening a character

### ISSUE THREAD

**Issue by imnachos** [ryceg/Eigengrau-s-Essential-Establishment-Generator#278] opened 2020-06-08 15:08 UTC
**Describe the bug**
Undefined error when opening a character

**To Reproduce**
I opened the site, created an "Alchemist", went to the shop. Clicked "Buy something". Looked around, then clicked on the shop owner's name and the pop up happened.

**Additional context**
I do have Ublock origins and Privacy Badger installed with latest firefox.

![bug](https://user-images.githubusercontent.com/15200679/84046316-4f537900-a980-11ea-81c4-b37af2c096c9.PNG)

**Comment by imnachos** [comment] 2020-06-08 15:09
After clicking "Ok", I clicked the JSON button at the top and the same happened

`Error: setup.articles.output(...) is undefined.

Stack Trace:
setup.profileTooltip/<@https://eigengrausgenerator.com/ line 56169 > eval:38167:63
e@https://eigengrausgenerator.com/:59:29453
l/</t<@https://eigengrausgenerator.com/:59:29755`

**Comment by ryceg** [comment] 2020-06-09 00:02
Please provide the seed (eigengrausgenerator.com/**#adjectiveadjectiveanimal**) in order for us to be able to diagnose the issue.

**Comment by imnachos** [comment] 2020-06-09 13:45
Oops, seems like I closed off the tab. Any way to track that down?

**Comment by ryceg** [comment] 2020-06-10 02:30
Unfortunately not.

**Comment by ryceg** [comment] 2020-06-10 03:04
Duplicate of #267

**Closed by ryceg** 2020-06-10 03:04 UTC
Labels: bug, duplicate
