### ISSUE TITLE
Bug in a Brothel

### ISSUE THREAD

**Issue by alidr16** [ryceg/Eigengrau-s-Essential-Establishment-Generator#530] opened 2021-02-18 06:36 UTC
**Describe the bug**

Within the brothel building of the town generated and selecting create NPC you are given a list of options such as gender, race, etc- it does not actually take these selections into account and randomly generates an NPC instead.

**To Reproduce (bugs MUST be replicable)**

Make a town, select a brothel within the town, create customer, input details of customer in menus, press 'Create NPC' and watch as your selected 'female elderly orcish regular' becomes a 'male human young adult pest' described below

Town Seed (click [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/wiki/FAQ#people-keep-talking-about-seeds-what-is-a-seed) for info):

#superficialTRUEtigershark

Page to navigate to, buttons to press, etc:

create scenario -> Brothel - create new building -> Brothel Name -> Customers -> as described above -> Create NPC

**Additional context**

I appreciate your resource! This is a great wicked tool and is extremely helpful! My table and I appreciate you!

**Comment by ryceg** [comment] 2021-04-02 06:31
Closing as it is a duplicate of #541

**Closed by ryceg** 2021-04-02 06:31 UTC
