### ISSUE TITLE
Setting Parameters Before Generation

### ISSUE THREAD

**Issue by gendernihilist** [ryceg/Eigengrau-s-Essential-Establishment-Generator#284] opened 2020-06-08 18:57 UTC
I would love for there to be a feature where you set the parameters as per the "Edit [Community Name]" function BEFORE the town generates, as it seems like trying to do that with an existing community leaves all kinds of holdovers from the initial community that was randomly rolled, including racial demographics and the names of places that retain the original placename. Being able to set a placename and all the other factors under the Edit function and hitting generate so it makes something from a clean slate would hopefully negate the issues with holdover elements hanging on.

**Comment by ryceg** [comment] 2020-06-09 00:10
Closing as this is a duplicate of #273, though feel free to add your comments to #273's thread.

**Closed by ryceg** 2020-06-09 00:10 UTC
Labels: New Feature
