### ISSUE TITLE
Information changing and corrupting

### ISSUE THREAD

**Issue by CadenWortman** [ryceg/Eigengrau-s-Essential-Establishment-Generator#295] opened 2020-06-09 22:06 UTC
**Describe the bug**
After Refreshing the page and reloading a town from a save, information was changed and errors started popping up on NPC info pages

**To Reproduce**
Town Hash (the bit that comes after eigengrausgenerator.com- typically in the format of #adjectiveadjectiveanimal):
Page to navigate to, buttons to press, etc: Unknown besides loading save and checking NPCs

**Additional context**
![image](https://user-images.githubusercontent.com/60162726/84205779-763ea780-aa73-11ea-957f-91434abb4746.png)

**Comment by ryceg** [comment] 2020-06-10 02:42
Can you please provide the seed and steps to reach the state of the screenshot? 

This looks like an issue with refreshing, but I can see no evidence of data corrupting or changing, just the NPC profile breaking- navigating away and back to the profile, it is fine. 

I'm marking this as a duplicate of #280 given the same output.

**Closed by ryceg** 2020-06-10 02:42 UTC
Labels: duplicate
