### ISSUE TITLE
page not loading anything 

### ISSUE THREAD

**Issue by mickeymousez321** [ryceg/Eigengrau-s-Essential-Establishment-Generator#304] opened 2020-07-05 17:47 UTC
When I open the page it instantly pops up an error message and then nothing on the page loads. 
![ss twn gen](https://user-images.githubusercontent.com/67872888/86538766-07177000-bec6-11ea-9501-cb4fc1124cd8.png)

**Comment by ryceg** [comment] 2020-07-06 00:37
Please provide the seed and steps to reproduce this issue.

**Comment by mickeymousez321** [comment] 2020-07-06 00:46
I dont have a seed im not sure what that is.
The steps to reproduce
1. Type in website address
2. Get error message
3. Page doesn't load anything
That picture is what I see as soon as I go to the website.

**Comment by ryceg** [comment] 2020-07-06 02:26
The seed is the part that comes after https://eigengrausgenerator.com/**#adjectiveadjectiveanimal**

**Comment by ryceg** [comment] 2020-07-07 05:23
Closing due to lack of information. I will reopen if there is a seed provided.

**Closed by ryceg** 2020-07-07 05:23 UTC

**Comment by mickeymousez321** [comment] 2020-07-08 09:52
There is nothing that comes after that part all I have is https://eigengrausgenerator.com/

**Comment by ryceg** [comment] 2020-07-09 02:10
Please try the following link: https://eigengrausgenerator.com/#creativewindybaiji

You should have the town of Hutherhammer.

**Comment by mickeymousez321** [comment] 2020-07-10 03:12
![error](https://user-images.githubusercontent.com/67872888/87112344-9069d200-c239-11ea-99b0-4e48d0b52310.png)
it did the same thing

**Comment by Glinkis** [comment] 2020-07-10 04:17
What browser/version är you using?

**Comment by mickeymousez321** [comment] 2020-07-10 06:04
I use Microsoft edge

**Comment by ryceg** [comment] 2020-07-10 06:22
Can you please try using Google Chrome and confirm that the issue still
persists?

**Comment by Glinkis** [comment] 2020-07-10 06:27
Which version of edge is that?

**Comment by mickeymousez321** [comment] 2020-07-10 15:02
i think its version 42.17134.1098.0 im no really sure where to find that information

**Comment by mickeymousez321** [comment] 2020-07-10 15:04
it actually did open on chrome
