### ISSUE TITLE
I generated a homosexual and ex-militia toddler.

### ISSUE THREAD

**Issue by davelens** [ryceg/Eigengrau-s-Essential-Establishment-Generator#592] opened 2021-04-25 19:30 UTC
**Describe the bug**

I generated an NPC, who had a number of associated relationships. One of them was a toddler, 1 year old, a peasant, ex-militia, and homosexual.

![dnd-ml-1](https://user-images.githubusercontent.com/221527/116006767-f5e25000-a60c-11eb-8850-23b2a94337b4.png)

**To Reproduce (bugs MUST be replicable)**

[Town Seed](https://eigengrausgenerator.com/#noisyfrigidestuarinecrocodile)

As you can see, the name of the toddler is Daenyel Deane.

**Additional context**

It's the first time I'm using the tool. I don't think I did anything wrong.

**Comment by ryceg** [comment] 2021-04-25 21:37
You win the "strangest issue title"! This is a duplicate of #263. I'll look into this.

**Closed by ryceg** 2021-04-25 21:37 UTC
