### ISSUE TITLE
Racial Demographics adjuster

### ISSUE THREAD

**Issue by arabwes** [ryceg/Eigengrau-s-Essential-Establishment-Generator#655] opened 2021-07-26 17:07 UTC
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_
I'm trying to replicate a town, Port Zoon, from the book, Explorer's Guide To Wildemount. It's a bit annoying to get the population numbers right because the total population is limited to 12000 and the percentages change every time I change any racial raw number. 

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._
I'd like to see the max population increase. 
I'd also like the percentage numbers to become editable text fields so someone can manually define the percent they want to see. Then to avoid having the percent dynamically change as other numbers are set, it would be beneficial to have an "apply" button to apply the settings that have been defined by the user for the population scope only and make the calculations afterwards. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ryceg** [comment] 2021-08-15 08:00
Closing as this is a duplicate of #645.

**Closed by ryceg** 2021-08-15 08:00 UTC
